version: "3.9"

services:
  nginx:
    image: bitnami/nginx:1.20
    ports:
      - 80:80
    volumes:
      - ./mynginx.conf:/opt/bitnami/nginx/conf/server_blocks/my_server_block.conf:ro
  web-app-1:
    # 提前打包好镜像 docker build -t my-web-app:1.0 .
    image: my-web-app:1.0
    environment:
      PORT: 8080
    ports:
      - 8080:8080
  web-app-2:
    image: my-web-app:1.0
    environment:
      PORT: 8080
    ports:
      - 8081:8080
  web-app-3:
    image: my-web-app:1.0
    environment:
      PORT: 8080
    ports:
      - 8082:8080
